# Generated by Django 6.0.4 on 2026-04-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_price_orderitem_subtotal_orderitem_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
